### ISSUE TITLE
test_env breaks non-trivial models.

### ISSUE THREAD

**Issue by klowrey** [Lyceum/LyceumBase.jl#22]
generating a random vector and using it to set a quat in mujoco is bad; mujoco normalizes the quat.

The test at 455 is invalid for models with quats.

The test at 478 is similar; mujoco will clip controls when they are outside of range.

The test at line 562 should reset both environments because for nontrivial environments warmstarts will be different between load and new forwards.

Test at line 582 does not pass when observation vectors are length 0.

Test at line 615 is related to 562. Resetting and calling forward can be different state than model load initial state. e1, e2 should be reset before t1 t2

**Comment by colinxs** [comment]
fixed in #24
